USE_TEMPORAL_SPLIT = False
USE_SHALLOW_DECODER = False
TRAIN_ONLY_GPS_FEATURES = False
GPS_DROPOUT_SEPARATELY = False
NO_SKIP_CONNECTION = False
NO_DROPOUT = False
TRAIN_ONLY_ONE_MODEL = False
MODEL_WIDTH = 32